### ISSUE TITLE
Name Changes in installation template

### ISSUE THREAD

**Issue by tbludau** [redhat-sap/sap-hana-deployment#8]
The last version, before this role was rebuild was build up to have a very dynamic installation template file. 

We try to find a solution in which all ansible parameters had the same naming specifications as they named in the configuration file. This was necessary to create a better collaboration between the linux and sap teams. We often had problems understanding what the other team meant. 
So we made a decision for this same names scenario. 
Another advantage was that nearly all parameters could be used and a lot of them could be used optionally because the standard values from the template were defined 

Take a look at the last version from Markus:
https://github.com/redhat-sap/sap-hana-deployment/blob/43b81ccd811ef03fc696e6c2689888f57bc5b302/templates/deployment_hana_inst_SID.cfg.j2

**Comment by tbludau** [comment]
Btw. the template file nearly changed with every new version (new features, etc.) perhaps it could be a good idea to have the possibility to use a file from the local system. But this is a feature request then... ;)

**Comment by berndfinger** [comment]
It looks like this issue is solved, looking at [the latest version of ](https://github.com/redhat-sap/sap-hana-deployment/blob/49d77129c461d93cc2065cbb1b8ae1520ad312e0/templates/configfile.j2).

Note: Development and maintenance of this software has stopped.

Its functional scope is covered and expanded by role [sap_hana_install](https://github.com/sap-linuxlab/community.sap_install/tree/main/roles/sap_hana_install).
The role is part of Ansible Collection [sap_install](https://github.com/sap-linuxlab/community.sap_install) in the
GitHub organization [sap-linuxlab](https://github.com/sap-linuxlab), which is a joint initiative by SAP Technology Partners.

If you believe that this issue is not fixed, may I please ask you to open a new issue in https://github.com/sap-linuxlab/community.sap_install/issues, with a title starting with "sap_hana_install: "?
